In [1]:
import warnings
warnings.filterwarnings("ignore")

acc=[]
pathw2v='C:\\a\\glove.6B.50d.txt'
w2vp = open(pathw2v, 'r',encoding='utf-8')
b=[]
for line in w2vp:
    b.append(line[:-1])
words = [str(i.split(' ')[0]) for i in b]
word2vector0= [i.split(' ')[1:51] for i in b]

In [2]:
word2vector=[[float(i) for i in j] for j in word2vector0]


In [3]:
worddic={}
for i in range(len(words)):
    worddic[words[i]]=i

In [4]:
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from pandas.core.frame import DataFrame
path = 'C:\\a\\opinions.tsv'
data = pd.read_table(path,header=None,skiprows=1,names=['Sentiment','Review'])
X=data.Review
y = data.Sentiment

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=1, test_size= 0.5)
print(len(y_train))

3458


In [6]:
from textblob import TextBlob
from textblob import Word

In [7]:
X_train_vector=[]
X_test_vector=[]
import numpy as np

In [8]:
for i in X_train:
    t1=TextBlob(str(i)).words
    t2=np.zeros(50)
    sum=0
    for j in t1:
        if j not in worddic:
            continue
        t3=np.array(word2vector[worddic[j.lower()]])
        t2=t2+t3
        sum+=1
    X_train_vector.append(t2/sum)
print(len(X_train_vector))

3458


In [9]:
for i in X_test:
    t1=TextBlob(i).words
    t2=np.zeros(50)
    sum=0
    for j in t1:
        if j not in worddic:
            continue
        t3=np.array(word2vector[worddic[j.lower()]])
        t2=t2+t3
        sum+=1
    X_test_vector.append(t2/sum)

print(len(X_test_vector))

3459


In [10]:
Y_train=[]
Y_test=[]


In [11]:
for i in y_train:
    Y_train.append(i)
print(len(Y_train))

3458


In [12]:
for i in y_test:
    Y_test.append(i)
print(len(Y_test))

3459


In [13]:
X_train_Vector=np.array(X_train_vector)

Y_Train=np.array(Y_train)
X_test_Vector=np.array(X_test_vector)
Y_Test=np.array(Y_test)

X_train_Vector=np.nan_to_num(X_train_Vector)
Y_Train=np.nan_to_num(Y_Train)
X_test_Vector=np.nan_to_num(X_test_Vector)
Y_Test=np.nan_to_num(Y_Test)
print(len(X_train_Vector))
print(len(Y_Train))

3458
3458


In [14]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB(priors=None)
clf.fit(X_train_Vector,Y_Train)
y_pred = clf.predict(X_test_Vector)
print('\nNaive Bayes')
acc.append(metrics.accuracy_score(Y_Test,y_pred)*100)
print('Accuracy Score: ',metrics.accuracy_score(Y_Test,y_pred)*100,'%',sep='')
print('Confusion Matrix: ',metrics.confusion_matrix(Y_Test,y_pred), sep = '\n')


Naive Bayes
Accuracy Score: 80.8326105810928%
Confusion Matrix: 
[[1077  409]
 [ 254 1719]]


In [15]:
LR = LogisticRegression()
LR.fit(X_train_Vector,Y_Train)
y_pred = LR.predict(X_test_Vector)
print('\nLogistic Regression')
acc.append(metrics.accuracy_score(Y_Test,y_pred)*100)
print('Accuracy Score: ',metrics.accuracy_score(Y_Test,y_pred)*100,'%',sep='')
print('Confusion Matrix: ',metrics.confusion_matrix(Y_Test,y_pred), sep = '\n')


Logistic Regression
Accuracy Score: 95.46111592945938%
Confusion Matrix: 
[[1413   73]
 [  84 1889]]


In [16]:
SVM = LinearSVC()
SVM.fit(X_train_Vector,Y_Train)
y_pred = SVM.predict(X_test_Vector)
print('\nSupport Vector Machine')
acc.append(metrics.accuracy_score(Y_Test,y_pred)*100)
print('Accuracy Score: ',metrics.accuracy_score(Y_Test,y_pred)*100,'%',sep='')
print('Confusion Matrix: ',metrics.confusion_matrix(Y_Test,y_pred), sep = '\n')



Support Vector Machine
Accuracy Score: 95.63457646718705%
Confusion Matrix: 
[[1425   61]
 [  90 1883]]


In [17]:
KNN = KNeighborsClassifier(n_neighbors = 3)
KNN.fit(X_train_Vector,Y_Train)
y_pred = KNN.predict(X_test_Vector)
print('\nK Nearest Neighbors (NN = 3)')
acc.append(metrics.accuracy_score(Y_Test,y_pred)*100)
print('Accuracy Score: ',metrics.accuracy_score(Y_Test,y_pred)*100,'%',sep='')
print('Confusion Matrix: ',metrics.confusion_matrix(Y_Test,y_pred), sep = '\n')


K Nearest Neighbors (NN = 3)
Accuracy Score: 94.6516334200636%
Confusion Matrix: 
[[1349  137]
 [  48 1925]]


In [18]:
X_all=[]
for i in X:
    t1=TextBlob(str(i)).words
    t2=np.zeros(50)
    sum=0
    for j in t1:
        if j not in worddic:
            continue
        t3=np.array(word2vector[worddic[j.lower()]])
        t2=t2+t3
        sum+=1
    X_all.append(t2/sum)
print(len(X_all))
Y_all=[]
for i in y:
    Y_all.append(i)
print(len(Y_all))
X_All=np.array(X_all)
Y_All=np.array(Y_all)


X_All=np.nan_to_num(X_All)
Y_All=np.nan_to_num(Y_All)



6917
6917


In [ ]:
LR_complete=LinearSVC()
LR_complete.fit(X_All,Y_All)
while True:
    test=input()
    print(test)
    test1=TextBlob(test).words
    t2=np.zeros(50)
    for j in test1:
            print(j)
            if j not in worddic:
                continue
            t3=np.array(word2vector[worddic[j.lower()]])
            t2=t2+t3
            sum+=1

    test_dtm=t2/sum
    test_dtm=np.nan_to_num([test_dtm])
    print(test_dtm)
    predLabel = LR_complete.predict(test_dtm)
    print(predLabel)
    tags = ['Negative','Positive']
    #Display Output
    print('The review is predicted',tags[int(predLabel[0])])

qiuyuqi is shanbaodi's son
qiuyuqi is shanbaodi's son
qiuyuqi
is
shanbaodi
's
son
[[ 0.14160875  0.253145   -0.10196125  0.0596025   0.32188875  0.19217375
  -0.20987326 -0.0258375  -0.05630625  0.0307625   0.0896015   0.20101
  -0.23909363 -0.18444087  0.16757875  0.07221888 -0.03155125  0.115986
  -0.08897     0.13703087 -0.13388539  0.144575   -0.1388605   0.00471375
   0.143606   -0.870675   -0.20841625 -0.05751625 -0.038473    0.04285387
   1.0901     -0.1559805  -0.11549     0.01289325  0.10638187 -0.07561825
   0.00496125  0.08302625  0.1009225  -0.08242875 -0.02156675  0.2152675
  -0.1958025  -0.17057263  0.00787263 -0.00456125 -0.15909    -0.29911875
   0.08520113  0.10268363]]
['1']
The review is predicted Positive
sbd is qyq's son
sbd is qyq's son
sbd
is
qyq
's
son
[[ 0.02036167  0.176927   -0.0432725   0.04878667  0.15172583  0.14886333
  -0.13735609 -0.14864167  0.0050625   0.00059583  0.07605517  0.22559
  -0.23045992  0.02528108 -0.0074725   0.14930425  0.04736083  0.069

In [20]:
from __future__ import print_function, division
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

x=['NB','LR','SVM','KNN']
